---
dist: xenial
sudo: true
language: generic

services:
- docker
os:
- linux

stages:
- name: devel
  if: branch = master
- name: release branch

jobs:
  include:
  - stage: devel
    script: .travis/build.sh
    deploy:
    - provider: script
      script: .travis/deploy-docker.sh dev
      on:
        branch: master

  - stage: release branch
    script: echo "travis branch = $TRAVIS_BRANCH, tag = $TRAVIS_TAG"; .travis/build.sh
    deploy:
    - provider: script
      script: .travis/deploy-docker.sh $TRAVIS_BRANCH
      on:
        condition: $TRAVIS_BRANCH =~ /^release-[0-9\.]+$/
