---
dist: xenial
sudo: true
language: generic

services:
- docker
os:
- linux

stages:
- name: devel
  if: branch = master
- name: release branch
  if: branch =~ /release-[0-9\.]+/

jobs:
  include:
  - stage: devel
    script: .travis/build.sh
    deploy:
    - provider: script
      script: .travis/deploy-docker.sh dev

  - stage: release branch
    script: echo "travis branch = $TRAVIS_BRANCH, tag = $TRAVIS_TAG"; .travis/build.sh
    deploy:
    - provider: script
      script: .travis/release-docker.sh $TRAVIS_BRANCH
